name: watchlist_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
